### ISSUE TITLE
filename of button icon doesn't match declaration in plugin.js

### ISSUE THREAD

**Issue by peterhebert** [pkerspe/ckeditor-bootstrap-accordionList#1]
The plugin declares the icon name in lower case:
`icons: 'accordionlist',`
however, the filename of the main icon is in a camel case: icons/accordionList.png
This is causing a 404 error on the file and the icon does not appear on the button in the ckeditor
![missing-button](https://user-images.githubusercontent.com/3053120/27005026-29286dfe-4dca-11e7-9ca2-0dc902d7b082.png)
Either the file should be renamed to 'accordionlist.png', or the icon declaration changed to 'accordionList' in plugin.js - line 3

**Comment by pkerspe** [comment]
thank you Peter, I fixed the issue in master branch.

**Comment by peterhebert** [comment]
I just noticed that the HiDPI version of the icon still has the lowercase filename - it should also be named 'accordionList.png'
