### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by santaclaus21** [pkerspe/ckeditor-bootstrap-accordionList#3]
1) CKE builder version is broken, no icons.
2) How to install manually:
a) plugin/accordianList (?) (directory name)
b) config > extraplugins: accordianList (?)
c) custom menu > what is a name fo button?

![image](https://user-images.githubusercontent.com/1121662/28307844-90e97d14-6ba4-11e7-953e-c006d1b17cc8.png)

Answers:
- github version is not working for me. Only version from CKEditor website named 0.4 version
2)
a) accordionList
b) accordionList
c) AccordionList

**Comment by pkerspe** [comment]
can you please specify your problems a bit more in detail?
What is the intention of the second part of your message starting with "answers"?

**Comment by santaclaus21** [comment]
- github version is working: my mistake. Something was cached.
- There is **no install** instruction enywhere (2 a,b,c) if you don't use CK Builder (where plugin is broken). 
Second part are my own answers for these questions.
