### ISSUE TITLE
Allowed content issue

### ISSUE THREAD

**Issue by a2exfr** [pkerspe/ckeditor-bootstrap-accordionList#7]
Hi. Some strange bug.
1- insert accordion widget + collapsable items save - it works good
2- open editor and save again and got unneeded html like this 

```
<div class="accordion-list">
<div aria-multiselectable="true" class="accordion-list-group accordion-list-items panel-group" id="accordion1506542607046" role="tablist">
<div class="collapsible-item panel panel-default" id="Collapsible1506542661001">
<div class="collapsible-item-heading panel-heading" id="headingCollapsible1506542661001" role="tab">
<h4 class="collapsible-item-title panel-title">

/unneeded/
<a aria-controls="collapseCollapsible1506542661001" aria-expanded="false" class="collapsed collapsible-item-title-link-icon" data-parent="#accordion1506542607046" data-toggle="collapse" href="#collapseCollapsible1506542661001" role="button"><em>&nbsp;</em></a>
/unneeded/

<a aria-controls="collapseCollapsible1506542661001" aria-expanded="false" class="collapsed collapsible-item-title-link" data-parent="#accordion1506542607046" data-toggle="collapse" href="#collapseCollapsible1506542661001" role="button">Title Text</a></h4>
</div>



<div aria-labelledby="headingCollapsible1506542661001" class="collapse collapsible-item-collapse panel-collapse" id="collapseCollapsible1506542661001" role="tabpanel">
<div class="collapsible-item-body panel-body">
<p>Body Text</p>
</div>
</div>
</div>
```

Can't figure that wrong. Collapsable item out of accordion work fine.
Also I have more then one editor on the page.

**Comment by a2exfr** [comment]
Solved.
1- ckeditor removing font classes so need to add to  allowedContent:   ` span(*)[*]` .  This also in collapsable item.
2- also ckeditor removes pull-right class from title of collapsible item  so the line that work for me.
` allowedContent: 'div(!collapsible-item*,panel*,collapse)[*];h4(!collapsible-item*,panel*)[*];a(!collapsible-item*,panel*,collapsed,pull-right*)[*];span(!glyphicon*)[*];p;br;span[*];ul;ol;li;strong;em;u;table[*];tbody;theader;tr;td;th;hr;a;a(!href,*)[*];span(*)[*]'`

Hope this will be useful for somebody

**Comment by pkerspe** [comment]
Thanks Alex, I will implement the fix asap

**Comment by pkerspe** [comment]
committed to master in commit b18197f9b2ed2e9fabed1f60497060e93137cea2
