### ISSUE TITLE
Allow 'a' and 'img' html tags in AccordionList

### ISSUE THREAD

**Issue by NullIsNot0** [pkerspe/ckeditor-bootstrap-accordionList#9]
To allow a and img tags in AccordionList change Line 14 in `plugin.js` from:

`allowedContent: 'div(!collapsible-item*,panel*,collapse)[*];h4(!collapsible-item*,panel*)[*];a(!collapsible-item*,panel*,collapsed,pull-right*)[*];p;br;ul;ol;li;strong;em;u;table[*];tbody;theader;tr;td;th;hr;a;a(!href,*)[*];span(*)[*]'`

to:

`allowedContent: 'div(!collapsible-item*,panel*,collapse)[*];h4(!collapsible-item*,panel*)[*];a(!collapsible-item*,panel*,collapsed,pull-right*)[*];p;br;ul;ol;li;strong;em;u;table[*];tbody;theader;tr;td;th;hr;a;a(*)[*];span(*)[*];img(*)[*]'`

**Comment by NullIsNot0** [comment]
And please don't forget to release new version when commit, so CKEditor online builder can build correctly working version.

**Comment by NullIsNot0** [comment]
Created a pull request for this issue. Please review and merge it.
#10

**Comment by pkerspe** [comment]
merged and creating new release right now
